Repository hellomouse/GNS, pull requests merged in 2018-10, with the labels that each got.

#42 Style Fixes
  dashboard/package-lock.json
  dashboard/src/App.css
  dashboard/src/GitHub.js
  dashboard/src/pages/RepoSettingsPage.js
  package-lock.json
Labels: enhancement

#15 Switch to use request-promise-native
  bot/index.js
  package-lock.json
  package.json
Labels: enhancement

#43 Update config to stable from create-react-app
  dashboard/.babelrc.js
  dashboard/.browserslistrc
  dashboard/.eslintrc.js
  dashboard/config/jest/babelTransform.js
  dashboard/config/jest/fileTransform.js
  dashboard/config/jest/graphqlTransform.js
  dashboard/config/paths.js
  dashboard/config/webpack.config.dev.js
  dashboard/config/webpack.config.prod.js
  dashboard/config/webpackDevServer.config.js
  dashboard/package-lock.json
  dashboard/package.json
  dashboard/scripts/build.js
  dashboard/scripts/start.js
  dashboard/scripts/test.js
  dashboard/src/index.js
Labels: dashboard

#48 Fix the async iteration
  bot/index.js
Labels: bug, 🤖probot

#47 Add typescript typings packages for dev environ
  package-lock.json
  package.json
Labels: PouchDB, dashboard, 🤖probot

#57 Fix requesting reviews from teams
  bot/index.js
Labels: 🤖probot

#55 Add issue.unlabeled`
  bot/index.js
Labels: 🤖probot

#61 Only use hellomouse IRC socket when in DEV
  bot/index.js
Labels: IRC, 🤖probot

#59 Add self to the CSP header
  bot/web.js
Labels: 🛡️security🔒, 🤖probot

#64 Add webpack-subresource-integrity plugin
  dashboard/config/webpack.config.prod.js
  dashboard/package-lock.json
  dashboard/package.json
Labels: ⚛️dashboard, 🛡️security🔒

#67 Fix push event
  bot/index.js
Labels: bug, 🤖probot
